### ISSUE TITLE
IP DSCP flag

### ISSUE THREAD

**Issue by fmadio** [fmadio/pcap2json#10]
add DSCP flags as part of the flow Hash + output the IP.DSCP into the flow data

**Comment by fmadio** [comment]
commited

**Comment by fmadio** [comment]
Outputs the raw DSCP numerical value, not sure if it should try enumerate the value into something more readable.

**Comment by navinsaven** [comment]
Perhaps converting the commonly used DSCP values as per https://en.wikipedia.org/wiki/Differentiated_services#Commonly_used_DSCP_values?

**Comment by fmadio** [comment]
Adding these strings in the JSON output ?

![image](https://user-images.githubusercontent.com/12390507/58929226-00816b00-8791-11e9-96d8-f2bb92ba7f12.png)

**Comment by fmadio** [comment]
included CS* values from here
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus1000/sw/4_0/qos/configuration/guide/nexus1000v_qos/qos_6dscp_val.pdf

**Comment by fmadio** [comment]
List of unknown DSCP values, good for now, closing

![image](https://user-images.githubusercontent.com/12390507/58929749-640c9800-8793-11e9-9084-3f2a76512eeb.png)

**Comment by navinsaven** [comment]
Yep. That's good. So the unknown values are in hex?

**Comment by fmadio** [comment]
Correct, if theres no string it writes it in hex. Data is from Interop17
